name: Isovalent Helm Action
description: Deploys a helm chart
author: Isovalent
inputs:
  release:
    description: Helm release name. Will be combined with track if set. (required)
    required: true
  namespace:
    description: Kubernetes namespace name. (required)
    required: true
  chart:
    description: Helm chart path.
    required: true
  version:
    description: chart version
    required: false
  values:
    description: Helm chart values, expected to be a YAML or JSON string.
    required: false
  dry-run:
    description: Simulate an upgrade.
    required: false
  value-files:
    description: Additional value files to apply to the helm chart. Expects JSON encoded
      array or a string.
    required: false
  timeout:
    description: The timeout for the help deployment
    required: false
  repo:
    description: A URL for a helm repo to install the chart from
    required: false
  atomic:
    description: If true, upgrade process rolls back changes made in case of failed upgrade. Defaults to false.
    required: false
runs:
  using: docker
  image: Dockerfile
