name: 'Test'
on: ['push']

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - name: Create kind cluster
        uses: helm/kind-action@fa81e57adff234b2908110485695db0f181f3c67
      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78
        with:
          version: v3.11.1
      - name: Create example-values.yaml
        run: |
          cat << EOF > example-values.yaml
          metrics:
            enabled: true
          EOF
      - name: 'Install a chart'
        uses: './'
        with:
          release: 'mysql'
          namespace: 'default'
          chart: 'mysql'
          repo: https://charts.bitnami.com/bitnami
          values: |
            fullnameOverride: mysql
          value-files: >-
            # Example values can be provided as a YAML or JSON list of strings,
            # where each string is a filename.
            - example-values.yaml

      - name: 'Install a chart that has CRDs'
        uses: './'
        with:
          release: 'kube-prometheus'
          namespace: 'monitoring'
          chart: 'kube-prometheus-stack'
          repo: https://prometheus-community.github.io/helm-charts
          version: 45.7.1
          upgrade-crds: true
          values: |
            fullnameOverride: prometheus-k8s
            cleanPrometheusOperatorObjectNames: true

      - name: 'Install a chart that has that use YAML implicit block mappings'
        uses: './'
        with:
          release: 'clickhouse-operator'
          namespace: 'clickhouse-operator'
          chart: 'altinity-clickhouse-operator'
          repo: https://docs.altinity.com/clickhouse-operator
          version: 0.20.3
          # needed to test CRD extraction logic for CRDs containing YAML implicit block mappings
          upgrade-crds: true
